[workspace]
authors = ["dohan <dyh0514@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "HRI_Drone_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build --packages-select hri_drone_project"
clean = "rm -rf build install log"

# env를 통해 라이브러리 경로(LD_LIBRARY_PATH)를 직접 박아넣습니다.
test_sensor = { cmd = "ros2 run hri_drone_project Test_Sensor_Node", env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH", AMENT_PREFIX_PATH = "$CONDA_PREFIX:$PWD/install/hri_drone_project" } }

test_processor = { cmd = "ros2 run hri_drone_project Signal_Processor_Test", env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH", AMENT_PREFIX_PATH = "$CONDA_PREFIX:$PWD/install/hri_drone_project" } }

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
cmake = ">=4.2.1,<5"
ninja = ">=1.13.2,<2"
clang-format = ">=21.1.0,<22"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-gazebo-ros-pkgs = ">=3.9.0,<4"
ros-humble-vision-opencv = ">=3.2.1,<4"
pyserial = ">=3.5,<4"
python = ">=3.11.14,<3.12"
jupyter = ">=1.1.1,<2"
setuptools = ">=80.9.0,<81"
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
eigen = ">=3.4.0,<4"
ros-humble-sensor-msgs = ">=4.9.0,<5"
gdb = ">=17.1,<18"
cppcheck = ">=2.18.3,<3"
ros-humble-tf2-geometry-msgs = ">=0.25.14,<0.26"
